### ISSUE TITLE
Feature task does not include own bundle

### ISSUE THREAD

**Issue by mbelling** [lburgazzoli/gradle-karaf-plugin#17]
I have a project that I am trying to create a feature and KAR for.  When I run the build, it generates the feature and the KAR, but the feature does not include the bundle for the project it is in, and as a result, the KAR also does not include the bundle.  I am using version 0.0.21, built locally.

I understand things are still under development, but I am more asking to make sure I did not do anything incorrectly.

```
karaf {
    features {
        feature {
            name = project.name
            description = 'Our ' + project.name + ' Feature'
        }
    }
    kar {
        enabled = true
    }
}
```

**Comment by mbelling** [comment]
From looking at the code, I found the 'includeProject' flag, but when I tried to set it to true:

```
:generateKar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateKar'.
> Cannot invoke method toPath() on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateKar'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
.....
....
Caused by: java.lang.NullPointerException: Cannot invoke method toPath() on null object
        at java_io_File$toPath$3.call(Unknown Source)
        at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask$_copy_closure2$_closure3.doCall(KarafKarTask.groovy:58)
        at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask$_copy_closure2.doCall(KarafKarTask.groovy:56)
        at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask.copy(KarafKarTask.groovy:55)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
....
....
```

**Comment by lburgazzoli** [comment]
Fixed in v0.0.22
includeProject moved to features block

**Comment by mbelling** [comment]
Thanks for the update.  Do you still publish your plugin to a maven repo someplace?  The latest I have been able to find is v0.0.15.

**Comment by lburgazzoli** [comment]
Not at the moment, I plan to re-publish it to maven central once reached a stable level.
