### ISSUE TITLE
Stack overview during deps walk with a particular dependency

### ISSUE THREAD

**Issue by yrashk** [lburgazzoli/gradle-karaf-plugin#23]
When I have this dependency in one of my subprojects:

```groovy
compile 'com.jcabi:jcabi-github:0.28'
```

the plugin throws `java.lang.StackOverflowError` (see below). As long as the dependency is removed, everything works just fine. Not exactly sure what's the culprit just yet.

```
Caused by: java.lang.StackOverflowError
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure6.doCall(KarafUtils.groovy:47)
	at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:42)
```

**Comment by yrashk** [comment]
I think I have an idea on what's happening.

[jcabi-github](http://mvnrepository.com/artifact/com.jcabi/jcabi-github/0.28) depends on [jcabi-aspects](http://mvnrepository.com/artifact/com.jcabi/jcabi-aspects/0.22.5), which depends on [jcabi-log](http://mvnrepository.com/artifact/com.jcabi/jcabi-log/0.17), which depends on jcabi-aspects again...

**Comment by lburgazzoli** [comment]
v0.0.32 released
