### ISSUE TITLE
GenerateKar task not working with some dependencies

### ISSUE THREAD

**Issue by eschizoid** [lburgazzoli/gradle-karaf-plugin#5]
The following gradle configuration is failing:

````
plugins {
	id 'com.github.lburgazzoli.karaf' version '0.0.13'
}

configurations {
	commons_io
	jpasskit
}

dependencies {
	commons_io "commons-io:commons-io:2.4"

	jpasskit "de.brendamour:jpasskit:0.0.8",
			"com.google.guava:guava:19.0",
			"org.bouncycastle:bcprov-jdk15on:1.52",
			"org.bouncycastle:bcpkix-jdk15on:1.52"
}

karaf {

	features {
		xsdVersion = '1.2.0'
		version = '4.0.0'
		description = 'Karaf archive of 3rd party dependencies for Synergy'

		repository "mvn:org.apache.karaf.cellar/apache-karaf-cellar/3.0.0/xml/features"
		repository "mvn:org.apache.karaf.features/enterprise/3.0.4/xml/features"
		repository "mvn:org.apache.karaf.features/enterprise/3.0.4/xml/features"
		repository "mvn:org.ops4j.pax.web/pax-web-features/3.1.0/xml/features"
		repository "mvn:org.apache.karaf.features/spring/3.0.4/xml/features"

		feature {
			feature name = 'commons-io'
			description = 'Apache Commons IO'
			version = "2.4"
			configurations = [
					project.configurations.commons_io
			]
		}

		feature {
			feature name = 'jpasskit'
			description = 'Java Library for Apple PassBook Web Service API'
			version = "0.0.8"
			configurations = [
					project.configurations.jpasskit
			]
		}
	}
}
````

The kar file is created when if I add the dependencies separately. However if I combine both of them I get the following stacktrace

````
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':coupons-dao:generateKar'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.UncheckedIOException: java.nio.file.FileAlreadyExistsException: /Users/magonzal/VirtualBox VMs/servicemixvm/shared_workspace/project-synergy/coupons-dao/build/karaf/kar/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.nio.file.FileAlreadyExistsException: /Users/magonzal/VirtualBox VMs/servicemixvm/shared_workspace/project-synergy/coupons-dao/build/karaf/kar/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
	at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask.copy(KarafKarTask.groovy:79)
	at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask$_copy_closure1$_closure2.doCall(KarafKarTask.groovy:54)
	at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask$_copy_closure1.doCall(KarafKarTask.groovy:50)
	at com.github.lburgazzoli.gradle.plugin.karaf.kar.KarafKarTask.copy(KarafKarTask.groovy:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	... 21 more
````

**Comment by lburgazzoli** [comment]
The problem is that commons-io:2.4 is transitive on jpasskit , I've fixed it in v0.0.14 by checking the existence of the file but best would be to exclude transitive dependencies in your dependencies/configurations block.

**Comment by eschizoid** [comment]
Yeah release `0.0.14` is generating this tag:

````
<feature name="jpasskit" version="0.0.8" description="Java Library for Apple PassBook Web Service API">
    <feature>jpasskit</feature>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-annotations/2.6.0</bundle>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-core/2.6.1</bundle>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-databind/2.6.1</bundle>
    <bundle>mvn:com.google.guava/guava/19.0</bundle>
    <bundle>mvn:commons-codec/commons-codec/1.10</bundle>
    <bundle>mvn:org.apache.commons/commons-lang3/3.4</bundle>
    <bundle>wrap:mvn:commons-collections/commons-collections/3.2</bundle>
    <bundle>wrap:mvn:commons-logging/commons-logging/1.0.4</bundle>
    <bundle>wrap:mvn:commons-httpclient/commons-httpclient/3.1</bundle>
    <bundle>mvn:org.slf4j/slf4j-api/1.7.2</bundle>
    <bundle>mvn:com.notnoop.apns/apns/1.0.0.Beta6</bundle>
    <bundle>wrap:mvn:javax.inject/javax.inject/1</bundle>
    <bundle>mvn:org.bouncycastle/bcprov-jdk15on/1.52</bundle>
    <bundle>mvn:org.bouncycastle/bcpkix-jdk15on/1.52</bundle>
    <bundle>mvn:commons-io/commons-io/2.4</bundle>
    <bundle>wrap:mvn:de.brendamour/jpasskit/0.0.8</bundle>
  </feature>
````

And i only want:

<feature name="jpasskit"
			 description="Java Library for Apple PassBook Web Service API"
			 version="${jpasskit.version}">
		<bundle dependency="true">wrap:mvn:de.brendamour/jpasskit/${jpasskit.version}</bundle>
		<bundle dependency="true">mvn:com.google.guava/guava/${guava.version}</bundle>
		<bundle dependency="true">wrap:mvn:org.bouncycastle/bcprov-jdk15on/${bouncycastle.version}</bundle>
		<bundle dependency="true">wrap:mvn:org.bouncycastle/bcpkix-jdk15on/${bouncycastle.version}</bundle>
	</feature>

Do i have to exclude all the transitive dependencies?

**Comment by lburgazzoli** [comment]
Potentially yes.

The plugin takes into account any dependency resolved by gradle including transitive ones. You can disable all the transitive deeps in dependencies/configurations blocks
