### ISSUE TITLE
Incorrect feature tag element.

### ISSUE THREAD

**Issue by eschizoid** [lburgazzoli/gradle-karaf-plugin#8]
When creating the kar file an extra `<feature>` element is getting generated in the xml file:

````
<feature name="jackson" version="2.6.2" description="Jackson JSON Libraries">
    <feature>jackson</feature>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-core/2.6.2</bundle>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-annotations/2.6.2</bundle>
    <bundle>mvn:com.fasterxml.jackson.core/jackson-databind/2.6.2</bundle>
    <bundle>mvn:com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.6.2</bundle>
    <bundle>mvn:joda-time/joda-time/2.1</bundle>
    <bundle>mvn:com.fasterxml.jackson.datatype/jackson-datatype-joda/2.6.2</bundle>
  </feature>
````

However the maven plugin generates only this:
````
<feature name="jackson" version="2.6.2" description="Jackson JSON Libraries">
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-core/2.6.2</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-annotations/2.6.2</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-databind/2.6.2</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.6.2</bundle>
        <bundle dependency="true">mvn:joda-time/joda-time/2.1</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.datatype/jackson-datatype-joda/2.6.2</bundle>
    </feature>
````

Please see that there is no `<feature>` element for the second xml.

When deploying the kar file (karaf 3.0.4) the following stack appears:

````
org.apache.karaf.features.core - 3.0.4 | Installing feature jackson 2.6.2
09:02:41,057 | ERROR | raf-3.0.4/deploy | fileinstall                      | 7 - org.apache.felix.fileinstall - 3.5.0 | In main loop, we have serious trouble
java.lang.StackOverflowError
        at org.apache.log4j.helpers.AbsoluteTimeDateFormat.format(AbsoluteTimeDateFormat.java:85)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at java.text.DateFormat.format(DateFormat.java:345)[:1.8.0_66]
        at org.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:443)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:65)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)[4:org.ops4j.pax.logging.pax-logging-service:1.8.3]
````

Seems that for some reason the dependency is not getting resolved.

**Comment by lburgazzoli** [comment]
Looks like there is a wrong element :

```groovy
feature {
   feature name = 'jpasskit'
}
```

Should be
```groovy
feature {
   name = 'jpasskit'
}
```
