### ISSUE TITLE
Support Gradle 8: Could not get unknown property 'classifier' for task ':postgresql:jar' of type org.gradle.api.tasks.bundling.Jar 

### ISSUE THREAD

**Issue by vlsi** [lburgazzoli/gradle-karaf-plugin#87]
`Property<String> AbstractArchiveTask.getArchiveClassifier()` is Gradle 5.1+

Here's the stacktrace:

```
groovy.lang.MissingPropertyException: Could not get unknown property 'classifier' for task ':postgresql:jar' of type org.gradle.api.tasks.bundling.Jar.
    at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
    at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyDescriptor.make(DependencyDescriptor.groovy:51)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeaturesUtils.groovy:74)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$_collectDependencies_closure1.doCall(KarafFeaturesUtils.groovy:43)
    at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:59)
    at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure3.doCall(KarafUtils.groovy:39)
    at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:37)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeaturesUtils.groovy:41)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyResolver.resolve(DependencyResolver.groovy:27)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2$_closure4$_closure5.doCall(KarafFeaturesTask.groovy:104)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2$_closure4.doCall(KarafFeaturesTask.groovy:69)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2.doCall(KarafFeaturesTask.groovy:68)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask.generateFeatures(KarafFeaturesTask.groovy:64)
    at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask.run(KarafFeaturesTask.groovy:53)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
    at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
    at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
    at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
    at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
    at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
    at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:93)
    at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
    at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:57)
    at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:54)
```

**Comment by vlsi** [comment]
Apparently, this has been fixed in https://github.com/lburgazzoli/gradle-karaf-plugin/pull/84.

@lburgazzoli would you please release a plugin so it is compatible with Gradle 8?

**Comment by lburgazzoli** [comment]
ok, by the end of the next week

**Comment by vlsi** [comment]
The workaround is

```kotlin
tasks.jar {
    extra.set("classifier", "")
    extra.set("extension", "jar")
}
```

**Comment by lburgazzoli** [comment]
release done https://plugins.gradle.org/plugin/com.github.lburgazzoli.karaf
